import { type Schema } from "./resource";
import {
  BedrockRuntimeClient,
  InvokeModelCommand,
} from "@aws-sdk/client-bedrock-runtime";

export const handler: Schema["PickHumanResponse"]["functionHandler"] = async (
  event,
  context
) => {
    console.log('Text Prompt Handler started - received prompt:', event.arguments.prompt);
    const AWS_REGION = process.env.AWS_REGION || "eu-west-2";

    const client = new BedrockRuntimeClient({
        region: AWS_REGION
    });

    const TEXT_MODEL_ID = process.env.MODEL_ID;
    if (!TEXT_MODEL_ID) {
        console.error('Missing MODEL_ID environment variable');
        throw new Error("MODEL_ID environment variable is not set");
    }
    
    // User prompt
    const prompt = event.arguments.prompt;

    const promptWithContext = `<s>[INST]
        Task: Decide which of the responses was generated by a human.
        Context: Party game where AI models answer prompts. The goal is to entertain. There are 2 AI answers and 1 human answer here. 
        Rules: 
        - Pick 1 answer and respond ONLY with the number of that answer (i.e respond with only the numbers 1, 2 or 3)

        Choose one of these sentences: ${prompt} [/INST]`;

    // Prepare the payload for the model.
    const payload = {
        "prompt": promptWithContext,
        "max_tokens": 10,
        "stop": [".", "\n", "!"],
        "temperature": 0.1,
        "top_p": 0.2,
        "top_k": 10
    }

    const command = new InvokeModelCommand({
        body: JSON.stringify(payload),
        modelId: TEXT_MODEL_ID,
    });

    const response = await client.send(command);
    
    const data = JSON.parse(Buffer.from(response.body).toString());

    console.log(`Received vote response from Bedrock model ${TEXT_MODEL_ID}`, data);

    if (data.outputs[0].stop_reason != "stop"){
        console.warn("AI model did not correctly finish generating response")
    }

    return data.outputs[0].text;
};